-- ============================================================================
-- BASE DE DATOS: Sistema de Control de Pagos - Estacionamiento Bloques 27-32
-- Versión: 1.0.0 (PostgreSQL / Supabase Version)
-- Fecha: 2026-01-25
-- Descripción: Schema completo para gestión de pagos mensuales (Compatible con PostgreSQL)
-- ============================================================================

-- En Supabase la base de datos ya existe, así que no hacemos DROP/CREATE DATABASE.
-- Usamos el esquema 'public' por defecto.

-- ============================================================================
-- TABLA: usuarios
-- ============================================================================
CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, -- Hash BCRYPT
    telefono VARCHAR(20),
    rol VARCHAR(50) NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente', 'operador', 'consultor', 'administrador')),
    activo BOOLEAN DEFAULT TRUE,

    -- Control de acceso y seguridad
    intentos_fallidos INT DEFAULT 0,
    bloqueado_hasta TIMESTAMP NULL,

    -- Flags para primer acceso
    primer_acceso BOOLEAN DEFAULT TRUE,
    password_temporal BOOLEAN DEFAULT TRUE,
    perfil_completo BOOLEAN DEFAULT FALSE,

    -- Exoneraciones
    exonerado BOOLEAN DEFAULT FALSE,
    motivo_exoneracion TEXT NULL,

    -- Auditoría
    fecha_registro TIMESTAMP DEFAULT NOW(),
    ultimo_acceso TIMESTAMP NULL
);

CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_rol ON usuarios(rol);
CREATE INDEX idx_usuarios_activo ON usuarios(activo);

-- ============================================================================
-- TABLA: apartamentos
-- ============================================================================
CREATE TABLE apartamentos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bloque VARCHAR(10) NOT NULL, -- Bloques: 27, 28, 29, 30, 31, 32
    escalera VARCHAR(5) NOT NULL, -- Escaleras: A, B, C
    piso INT NOT NULL,
    numero_apartamento VARCHAR(10) NOT NULL, -- Ej: 501, 502
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT NOW(),

    CONSTRAINT unique_apartamento UNIQUE (bloque, escalera, piso, numero_apartamento)
);

CREATE INDEX idx_apartamentos_bloque ON apartamentos(bloque);
CREATE INDEX idx_apartamentos_activo ON apartamentos(activo);

-- ============================================================================
-- TABLA: apartamento_usuario
-- ============================================================================
CREATE TABLE apartamento_usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartamento_id INT NOT NULL REFERENCES apartamentos(id) ON DELETE CASCADE,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    cantidad_controles INT DEFAULT 0,
    fecha_asignacion TIMESTAMP DEFAULT NOW(),
    activo BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_au_apartamento ON apartamento_usuario(apartamento_id);
CREATE INDEX idx_au_usuario ON apartamento_usuario(usuario_id);
CREATE INDEX idx_au_activo ON apartamento_usuario(activo);

-- ============================================================================
-- TABLA: controles_estacionamiento
-- ============================================================================
CREATE TABLE controles_estacionamiento (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartamento_usuario_id INT NULL REFERENCES apartamento_usuario(id) ON DELETE SET NULL,

    -- Identificación del control
    posicion_numero INT NOT NULL, -- Posición física: 1-250
    receptor VARCHAR(1) NOT NULL CHECK (receptor IN ('A', 'B')),
    numero_control_completo VARCHAR(10) NOT NULL UNIQUE, -- Ej: 1A, 15B
    
    -- Estado del control
    estado VARCHAR(20) DEFAULT 'vacio' CHECK (estado IN ('activo', 'suspendido', 'desactivado', 'perdido', 'bloqueado', 'vacio')),
    motivo_estado TEXT NULL,
    fecha_estado TIMESTAMP DEFAULT NOW(),

    -- Aprobaciones
    aprobado_por INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_asignacion TIMESTAMP NULL,

    CONSTRAINT unique_posicion_receptor UNIQUE (posicion_numero, receptor)
);

CREATE INDEX idx_controles_estado ON controles_estacionamiento(estado);
CREATE INDEX idx_controles_posicion ON controles_estacionamiento(posicion_numero);
CREATE INDEX idx_controles_receptor ON controles_estacionamiento(receptor);

-- ============================================================================
-- TABLA: configuracion_tarifas
-- ============================================================================
CREATE TABLE configuracion_tarifas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_mensual_usd DECIMAL(10, 2) NOT NULL DEFAULT 1.00,
    fecha_vigencia_inicio DATE NOT NULL,
    fecha_vigencia_fin DATE NULL,
    activo BOOLEAN DEFAULT TRUE,
    creado_por INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_creacion TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_tarifas_vigencia ON configuracion_tarifas(fecha_vigencia_inicio, fecha_vigencia_fin);
CREATE INDEX idx_tarifas_activo ON configuracion_tarifas(activo);

-- ============================================================================
-- TABLA: tasa_cambio_bcv
-- ============================================================================
CREATE TABLE tasa_cambio_bcv (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tasa_usd_bs DECIMAL(10, 4) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT NOW(),
    registrado_por INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fuente VARCHAR(100) DEFAULT 'Manual'
);

CREATE INDEX idx_tasa_fecha ON tasa_cambio_bcv(fecha_registro);

-- ============================================================================
-- TABLA: mensualidades
-- ============================================================================
CREATE TABLE mensualidades (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartamento_usuario_id INT NOT NULL REFERENCES apartamento_usuario(id) ON DELETE CASCADE,

    -- Período
    mes INT NOT NULL,
    anio INT NOT NULL,

    -- Snapshot
    cantidad_controles INT NOT NULL,
    monto_usd DECIMAL(10, 2) NOT NULL,
    monto_bs DECIMAL(12, 2) NOT NULL,
    tasa_cambio_id INT NOT NULL REFERENCES tasa_cambio_bcv(id),

    -- Estado
    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagado', 'vencido')),
    fecha_vencimiento DATE NOT NULL,
    fecha_generacion TIMESTAMP DEFAULT NOW(),
    bloqueado BOOLEAN DEFAULT FALSE,

    CONSTRAINT unique_mensualidad UNIQUE (apartamento_usuario_id, mes, anio)
);

CREATE INDEX idx_mensualidades_estado ON mensualidades(estado);
CREATE INDEX idx_mensualidades_vencimiento ON mensualidades(fecha_vencimiento);
CREATE INDEX idx_mensualidades_mes_anio ON mensualidades(mes, anio);

-- ============================================================================
-- TABLA: pagos
-- ============================================================================
CREATE TABLE pagos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartamento_usuario_id INT NOT NULL REFERENCES apartamento_usuario(id) ON DELETE CASCADE,

    -- Recibo oficial
    numero_recibo VARCHAR(20) NOT NULL UNIQUE,

    -- Montos
    monto_usd DECIMAL(10, 2) NOT NULL,
    monto_bs DECIMAL(12, 2) NOT NULL,
    tasa_cambio_id INT NOT NULL REFERENCES tasa_cambio_bcv(id),
    moneda_pago VARCHAR(50) NOT NULL CHECK (moneda_pago IN ('usd_efectivo', 'bs_transferencia', 'bs_efectivo')),

    -- Fechas
    fecha_pago TIMESTAMP DEFAULT NOW(),

    -- Comprobante
    comprobante_ruta VARCHAR(255) NULL,
    estado_comprobante VARCHAR(20) DEFAULT 'no_aplica' CHECK (estado_comprobante IN ('pendiente', 'aprobado', 'rechazado', 'no_aplica')),
    motivo_rechazo TEXT NULL,

    -- Aprobación
    registrado_por INT NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    aprobado_por INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_aprobacion TIMESTAMP NULL,

    -- Reconexión
    es_reconexion BOOLEAN DEFAULT FALSE,
    monto_reconexion_usd DECIMAL(10, 2) NULL DEFAULT 2.00,

    -- Sincronización
    google_sheets_sync BOOLEAN DEFAULT FALSE,
    fecha_sync TIMESTAMP NULL,

    -- Notas
    notas TEXT NULL
);

CREATE INDEX idx_pagos_numero_recibo ON pagos(numero_recibo);
CREATE INDEX idx_pagos_fecha_pago ON pagos(fecha_pago);
CREATE INDEX idx_pagos_estado_comprobante ON pagos(estado_comprobante);

-- ============================================================================
-- TABLA: pago_mensualidad
-- ============================================================================
CREATE TABLE pago_mensualidad (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id INT NOT NULL REFERENCES pagos(id) ON DELETE CASCADE,
    mensualidad_id INT NOT NULL REFERENCES mensualidades(id) ON DELETE CASCADE,
    monto_aplicado_usd DECIMAL(10, 2) NOT NULL,
    fecha_aplicacion TIMESTAMP DEFAULT NOW(),

    CONSTRAINT unique_pago_mensualidad UNIQUE (pago_id, mensualidad_id)
);

CREATE INDEX idx_pm_pago ON pago_mensualidad(pago_id);
CREATE INDEX idx_pm_mensualidad ON pago_mensualidad(mensualidad_id);

-- ============================================================================
-- TABLA: solicitudes_cambios
-- ============================================================================
CREATE TABLE solicitudes_cambios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apartamento_usuario_id INT NOT NULL REFERENCES apartamento_usuario(id) ON DELETE CASCADE,

    tipo_solicitud VARCHAR(50) NOT NULL CHECK (tipo_solicitud IN ('cambio_cantidad_controles', 'suspension_control', 'desactivacion_control')),
    
    cantidad_controles_nueva INT NULL,
    control_id INT NULL REFERENCES controles_estacionamiento(id) ON DELETE SET NULL,
    motivo TEXT NOT NULL,

    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
    fecha_solicitud TIMESTAMP DEFAULT NOW(),

    aprobado_por INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_respuesta TIMESTAMP NULL,
    observaciones TEXT NULL
);

CREATE INDEX idx_solicitudes_estado ON solicitudes_cambios(estado);
CREATE INDEX idx_solicitudes_tipo ON solicitudes_cambios(tipo_solicitud);
CREATE INDEX idx_solicitudes_fecha ON solicitudes_cambios(fecha_solicitud);

-- ============================================================================
-- TABLA: notificaciones
-- ============================================================================
CREATE TABLE notificaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,

    tipo VARCHAR(50) NOT NULL CHECK (tipo IN (
        'alerta_3_meses',
        'alerta_bloqueo',
        'comprobante_rechazado',
        'pago_aprobado',
        'solicitud_aprobada',
        'solicitud_rechazada',
        'bienvenida',
        'password_cambiado'
    )),

    titulo VARCHAR(255) NOT NULL,
    mensaje TEXT NOT NULL,

    leido BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    fecha_lectura TIMESTAMP NULL,

    email_enviado BOOLEAN DEFAULT FALSE,
    fecha_email TIMESTAMP NULL
);

CREATE INDEX idx_notif_usuario_leido ON notificaciones(usuario_id, leido);
CREATE INDEX idx_notif_tipo ON notificaciones(tipo);
CREATE INDEX idx_notif_fecha ON notificaciones(fecha_creacion);

-- ============================================================================
-- TABLA: logs_actividad
-- ============================================================================
CREATE TABLE logs_actividad (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NULL REFERENCES usuarios(id) ON DELETE SET NULL,

    accion VARCHAR(255) NOT NULL,
    modulo VARCHAR(50) NULL,

    tabla_afectada VARCHAR(50) NULL,
    registro_id INT NULL,
    datos_anteriores JSONB NULL,
    datos_nuevos JSONB NULL,

    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    fecha_hora TIMESTAMP DEFAULT NOW()
);

CREATE INDEX idx_logs_usuario ON logs_actividad(usuario_id);
CREATE INDEX idx_logs_modulo ON logs_actividad(modulo);
CREATE INDEX idx_logs_tabla ON logs_actividad(tabla_afectada);
CREATE INDEX idx_logs_fecha ON logs_actividad(fecha_hora);

-- ============================================================================
-- TABLA: password_reset_tokens
-- ============================================================================
CREATE TABLE password_reset_tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,

    codigo VARCHAR(6) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT NOW(),
    fecha_expiracion TIMESTAMP NULL,

    usado BOOLEAN DEFAULT FALSE,
    intentos_validacion INT DEFAULT 0,

    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL
);

CREATE INDEX idx_tokens_codigo ON password_reset_tokens(codigo);
CREATE INDEX idx_tokens_email ON password_reset_tokens(email);
CREATE INDEX idx_tokens_expiracion ON password_reset_tokens(fecha_expiracion);

-- ============================================================================
-- TABLA: login_intentos
-- ============================================================================
CREATE TABLE login_intentos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    ip_address VARCHAR(45) NOT NULL,
    user_agent TEXT NULL,
    fecha_hora TIMESTAMP DEFAULT NOW(),
    exitoso BOOLEAN DEFAULT FALSE,
    intentos INT DEFAULT 1,
    ultimo_intento TIMESTAMP DEFAULT NOW(),
    bloqueado_hasta TIMESTAMP NULL
);

CREATE INDEX idx_login_email ON login_intentos(email);
CREATE INDEX idx_login_ip ON login_intentos(ip_address);

-- ============================================================================
-- TABLA: configuracion_cron
-- ============================================================================
CREATE TABLE configuracion_cron (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tarea VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT NULL,
    script_path VARCHAR(255) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    frecuencia VARCHAR(100) NOT NULL,
    hora_ejecucion TIME NULL,
    dia_mes INT NULL,
    ultima_ejecucion TIMESTAMP NULL,
    ultimo_resultado VARCHAR(20) DEFAULT 'pendiente' CHECK (ultimo_resultado IN ('exitoso', 'fallido', 'pendiente')),
    ultimo_mensaje TEXT NULL
);

CREATE INDEX idx_cron_nombre ON configuracion_cron(nombre_tarea);
CREATE INDEX idx_cron_activo ON configuracion_cron(activo);

-- ============================================================================
-- VISTAS
-- ============================================================================

CREATE OR REPLACE VIEW vista_morosidad AS
SELECT
    u.id AS usuario_id,
    u.nombre_completo,
    u.email,
    u.telefono,
    CONCAT(a.bloque, '-', a.numero_apartamento) AS apartamento,
    au.cantidad_controles,
    COUNT(m.id) AS meses_pendientes,
    SUM(m.monto_usd) AS total_deuda_usd,
    SUM(m.monto_bs) AS total_deuda_bs,
    MIN(m.fecha_vencimiento) AS primer_mes_pendiente,
    MAX(m.fecha_vencimiento) AS ultimo_mes_pendiente,
    CASE
        WHEN COUNT(m.id) >= 4 THEN 'Bloqueado'
        WHEN COUNT(m.id) >= 3 THEN 'Alerta'
        ELSE 'Normal'
    END AS estado_morosidad
FROM usuarios u
JOIN apartamento_usuario au ON au.usuario_id = u.id AND au.activo = TRUE
JOIN apartamentos a ON a.id = au.apartamento_id
JOIN mensualidades m ON m.apartamento_usuario_id = au.id AND m.estado IN ('pendiente', 'vencido')
WHERE u.rol = 'cliente' AND u.activo = TRUE AND u.exonerado = FALSE
GROUP BY u.id, u.nombre_completo, u.email, u.telefono, a.bloque, a.numero_apartamento, au.cantidad_controles;

CREATE OR REPLACE VIEW vista_controles_vacios AS
SELECT
    c.id,
    c.posicion_numero,
    c.receptor,
    c.numero_control_completo,
    c.estado
FROM controles_estacionamiento c
WHERE c.estado = 'vacio' AND c.apartamento_usuario_id IS NULL
ORDER BY c.posicion_numero, c.receptor;

-- ============================================================================
-- DATOS INICIALES
-- ============================================================================

INSERT INTO configuracion_tarifas (monto_mensual_usd, fecha_vigencia_inicio, fecha_vigencia_fin, activo)
VALUES (1.00, '2025-01-01', NULL, TRUE);

INSERT INTO tasa_cambio_bcv (tasa_usd_bs, registrado_por, fuente)
VALUES (36.50, NULL, 'Inicial');

-- Usuarios admin por defecto (opcional)
-- INSERT INTO usuarios ...
